version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  nestjs-app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
